### ISSUE TITLE
I can't access patch expansion file

### ISSUE THREAD

**Issue by neilmaledev** [agamemnus/cordova-plugin-xapkreader#114]
main expansion file is working fine but my newly created patch expansion file is not accessible. I put them on the same directory with the same structure inside

obb/appname/main.1.appname.obb
obb/appname/patch.1.appname.obb

This is working fine with the main expansion file
content://oneminute.change.app/expansion/cloud.jpg

But this is not working in patch expansion file
content://oneminute.change.app/expansion/moon.jpg

STRUCTURE is simply like this on both main & patch:
/expansion/fileshere.*

Am I missing something? Any help is appreciated. TIA.

**Comment by agamemnus** [comment]
Looks correct. I wonder if one of the patches over the years only looked at
one path/file instead of two...

**Comment by neilmaledev** [comment]
Oh I double check my code and it seems that its just my mistake. It's working now, Sorry.

I just have another question, let me show a quick illustration

== START OF ILLUSTRATION ==

RELEASE 0
APK (80mb)

RELEASE 1
- APK (80mb)
- main.1.expansion.obb (40mb)
TOTAL SIZE (120mb)

RELEASE 2 
- APK (80mb)
- main.1.expansion.obb (40mb) - same with RELEASE 1
- patch.1.expansion.obb (20mb)
TOTAL SIZE (140mb)

RELEASE 3
- APK (80mb)
- main.1.expansion.obb (40mb) - same with RELEASE 1
- patch1.expansion.obb (20mb) - (my expectation is, this will stay)
- patch2.expansion.obb (10mb)
TOTAL SIZE (150mb) - expected
REALITY? (130mb)

== END OF ILLUSTRATION ==

Now, I'm wondering if the files on RELEASE 2 patch1 will remain on the app after the RELEASE 3 or it will be removed and patch2 will take place?

Because what I want is to keep all the files on every patch updates. Currently (RELEASE 1), I don't have any idea on how my next release behaves. What makes me curious the most is on RELEASE 3. Any clearer explanation is appreciated. BTW Thanks.

**Comment by agamemnus** [comment]
The last patch expansion is overwritten.

Anyone who downloads the app only gets the latest ones, so you can't try
using the browser cache as a trick, either.

On Oct 3, 2017 5:18 AM, "Neil Male" <notifications@github.com> wrote:

Oh I double check my code and it seems that its just my mistake. It's
working now, Sorry.

I just have another question, let me show a quick illustration

RELEASE 0
APK (80mb)

RELEASE 1

   - APK (80mb)
   - main.1.expansion.obb (40mb)
   TOTAL SIZE (120mb)

RELEASE 2

   - APK (80mb)
   - main.1.expansion.obb (40mb) - same with RELEASE 1
   - patch.1.expansion.obb (20mb)
   TOTAL SIZE (140mb)

RELEASE 3
APK (80mb)

   - main.1.expansion.obb (40mb) - same with RELEASE 1
   - patch1.expansion.obb (20mb) - (my expectation is, this will stay)
   - patch2.expansion.obb (10mb)
   TOTAL SIZE (150mb) - expected
   REALITY? (130mb)

== END OF ILLUSTRATION =

Now, I'm wondering if the files on RELEASE 2 patch1 will remain on the app
after the RELEASE 3 or it will be removed and patch2 will take place?

Because what I want is to keep all the files on every patch updates.
Currently (RELEASE 1), I don't have any idea on how my next release
behaves. What makes me curious the most is on RELEASE 3. Any clearer
explanation is appreciated. BTW Thanks.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/agamemnus/cordova-plugin-xapkreader/issues/114#issuecomment-333786387>,
or mute the thread

**Comment by neilmaledev** [comment]
Okay THX
