### ISSUE TITLE
5.3.1.

### ISSUE THREAD

**Issue by agamemnus** [agamemnus/cordova-plugin-xapkreader#26]
Cordova 5+ uses only gradle, so changes had to be made to the coding. Cordova 5 also uses a mandatory whitelist plugin by default, so we need to account for that.

5.3.1 fixes the library naming issues of 5 through ???. No more messing around with that.

https://github.com/agamemnus/cordova-plugin-xapkreader/tree/cordova-5.3.1

For anyone upgrading, please let me know how it goes.

Thanks again to everyone who contributed debugging, testing, and writing instructions. Here are the steps. First, install:

1) `cordova plugin add cordova plugin add https://github.com/agamemnus/cordova-plugin-xapkreader.git#cordova-5.3.1`
2) In `plugins/com.flyingsoftgames.xapkreader/plugin.xml`, set `xapk_expansion_authority` and  `plugins/com.flyingsoftgames.xapkreader` (untested by me -- if this doesn't work, try modifying android.json instead).
3) `cordova add platform android`
4) `cordova run android` (with the device connected and .obb file loaded on the device)

5) Now, if you are having trouble with the automatic OBB downloader (it should start if OBBs are missing, but in RELEASE mode only and using the Google Play APK only (??questionable??)), do this: in ``platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java``, change ``return isDebug;`` to ``return true;``.

6) Cordova 5 has a whitelist plugin requirement -- cordova-plugin-whitelist. At present, it is bugged and you need to add in some extra stuff to make sure your files are able to be read (due to too-restrictive default security)
You can do it one of two ways (or both):
6A) In your ``index.html`` file, you also need to add a Content-Security-Policy meta tag. Note that the instructions on the whitelist plugin on github do not show the most permissive meta tag and forget about ``content://`` or ``cdvfile://``. The most permissive meta tag seems to be: ``<meta http-equiv="Content-Security-Policy" content="* * 'self' default-src 'unsafe-inline' 'unsafe-eval' http://* https://* data: cdvfile://* content://*;">``. (content:// and cdvfile:// should really be included by default. If you want to omit those, I made a patch here: https://github.com/agamemnus/cordova-plugin-whitelist)
6B) Make sure to add ``allow-navigation``, and ``allow-intent``, and extra ``access origin`` tags to ``root/config.xml``. E.G.:
````
    <allow-navigation href="*://*/*"/>
    <allow-intent href="*" />
    <access origin="*" />
    <access origin="content:///*" />
    <access origin="cdvfile:///*" />
````

NOTE: Please do not post any logs here unless needed for showing any error you might have.

**Comment by Shinji89** [comment]
Hi,
First, thank you for the updates :) I tried your guide but i get and error during 'cordova build android':
`:compileArmv7DebugJavaC:\myproject\platforms\android\src\com\flyingsoftgames\xapkreader\XAPKAlarmReceiver.java:3: error: package com.google.android.vending.expansion.downloader does not exist`

At 2° step of your guide i also did "in android.json, look for and modify ``com.test.expansion`` and ``YOUR_GOOGLE_PLAY_LICENSE_KEY``" is it correct ?

**Comment by agamemnus** [comment]
Yes, you need to modify those in android.json, my bad.

**Comment by agamemnus** [comment]
I will look again but com.google.android.vending.expansion.downloader should definitely exist. Are you using 5.3.1 along with a fresh Android platform install?

**Comment by agamemnus** [comment]
Ok, it looks like something isn't being added which I thought was. Stay tuned.

**Comment by agamemnus** [comment]
I totally messed up and copied gh-pages by accident instead of my test version. Should be mostly fixed now. Looks like it's all running out of the box. There is a non-fatal error with com.google.play.services though. Looking into it.

**Comment by Shinji89** [comment]
Yes Agamemnus, now it works :)

**Comment by agamemnus** [comment]
Looks like I overwrote the readme to the original... I thought I changed it back to the new one. @Shinji89, can you look to see if you have the readme from before yesterday?

**Comment by Shinji89** [comment]
This is the content of my readme.md:

I forked this repository from katzer/cordova-plugin-local-notifications and made changes to the plugin.xml in order for it to be compatible with the PushPlugin plugin. Furthermore, I updated the plugin to use cordova-plugin-device instead of org.apache.cordova.device (deprecated). I made the changes on line 26 and 136 of plugin.xml.

[![PayPayl donate button](https://img.shields.io/badge/paypal-donate-yellow.svg)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=L3HKQCD9UA35A "Donate once-off to this project using Paypal")

#### :bangbang: Please vote for that cordova-windows issue :bangbang:
https://issues.apache.org/jira/browse/CB-8674

Thanks a lot!

Cordova Local-Notification Plugin
=================================

The essential purpose of local notifications is to enable an application to inform its users that it has something for them — for example, a message or an upcoming appointment — when the application isn’t running in the foreground.<br>
They are scheduled by an application and delivered on the same device.

<img width="35%" align="right" hspace="19" vspace="12" src="https://github.com/katzer/cordova-plugin-local-notifications/blob/example/images/android.png"></img>

### How they appear to the user
Users see notifications in the following ways:
- Displaying an alert or banner
- Badging the app’s icon
- Playing a sound


### Examples of Notification Usage
Local notifications are ideally suited for applications with time-based behaviors, such as calendar and to-do list applications. Applications that run in the background for the limited period allowed by iOS might also find local notifications useful.<br>
For example, applications that depend on servers for messages or data can poll their servers for incoming items while running in the background; if a message is ready to view or an update is ready to download, they can then present a local notification immediately to inform their users.


## Supported Platforms
The current 0.8 branch supports the following platforms:
- __iOS__ _(including iOS8)_<br>
- __Android__ _(SDK >=7)_
- __Windows 8.1__ _(added with v0.8.2)_
- __Windows Phone 8.1__ _(added with v0.8.2)_

Find out more informations [here][wiki_platforms] in our wiki.


## Installation
The plugin is installable from source and available on Cordova Plugin Registry and PhoneGap Build.

Find out more informations [here][wiki_installation] in our wiki.


## I want to get a quick overview
All wiki pages contain samples, but for a quick overview the sample section may be the fastest way.

Find out more informations [here][wiki_samples] in our wiki.


## I want to get a deep overview
The plugin supports scheduling local notifications in various ways with a single interface. It also allows you to update, clear or cancel them. There are different interfaces to query for local notifications and a complete set of events to hook into the life cycle of local notifications.

Find out more about how to schedule single, multiple, delayed or repeating local notifications [here][wiki_schedule].<br>
Informations about events like _click_ or _trigger_ can be found [here][wiki_events].

To get a deep overview we recommend to read about all the topics in our [wiki][wiki] and try out the [Kitchen Sink App][wiki_kitchensink]


## I want to see the plugin in action
The plugin offers a kitchen sink sample app. Check out the cordova project and run the app directly from your command line or preferred IDE.

Find out more informations [here][wiki_kitchensink] in our wiki.


## What's new
We are proud to announce our newest release version 0.8.x. Beside the hard work at the office and at the weekends it contains a lot of goodies, new features and easy to use APIs.

Find out more informations [here][wiki_changelog] in our wiki.


## Sample
The sample demonstrates how to schedule a local notification which repeats every week. The listener will be called when the user has clicked on the local notification.

```javascript
cordova.plugins.notification.local.schedule({
    id: 1,
    title: "Production Jour fixe",
    text: "Duration 1h",
    firstAt: monday_9_am,
    every: "week",
    sound: "file://sounds/reminder.mp3",
    icon: "http://icons.com/?cal_id=1",
    data: { meetingId:"123#fg8" }
});

cordova.plugins.notification.local.on("click", function (notification) {
    joinMeeting(notification.data.meetingId);
});
```

Find out more informations [here][wiki_samples] in our wiki.


## I would like to propose new features
We appricate any feature proposal and support for their development. Please describe them [here][feature_proposal_issue].

Find out more informations [here][wiki_next] in our wiki.

## Supporting
Your support is needed. If you use the plugin please send us a drop through the donation button.

Thank you!

[![PayPayl donate button](https://img.shields.io/badge/paypal-donate-yellow.svg)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=L3HKQCD9UA35A "Donate once-off to this project using Paypal")


## Contributing

1. Fork it
2. Create your feature branch (`git checkout -b my-new-feature`)
3. Commit your changes (`git commit -am 'Add some feature'`)
4. Push to the branch (`git push origin my-new-feature`)
5. Create new Pull Request


## License

This software is released under the [Apache 2.0 License][apache2_license].

© 2013-2015 appPlant UG, Inc. All rights reserved


[cordova]: https://cordova.apache.org
[wiki]: https://github.com/katzer/cordova-plugin-local-notifications/wiki
[wiki_platforms]: https://github.com/katzer/cordova-plugin-local-notifications/wiki/02.-Platforms
[wiki_installation]: https://github.com/katzer/cordova-plugin-local-notifications/wiki/03.-Installation
[wiki_kitchensink]: https://github.com/katzer/cordova-plugin-local-notifications/tree/example
[wiki_schedule]: https://github.com/katzer/cordova-plugin-local-notifications/wiki/04.-Scheduling
[wiki_events]: https://github.com/katzer/cordova-plugin-local-notifications/wiki/09.-Events
[wiki_samples]: https://github.com/katzer/cordova-plugin-local-notifications/wiki/11.-Samples
[wiki_changelog]: https://github.com/katzer/cordova-plugin-local-notifications/wiki/Upgrade-Guide
[wiki_next]: https://github.com/katzer/cordova-plugin-local-notifications/wiki/Feature-Requests
[feature_proposal_issue]: https://github.com/katzer/cordova-plugin-local-notifications/issues/451
[apache2_license]: http://opensource.org/licenses/Apache-2.0

**Comment by agamemnus** [comment]
I meant the readme from my project, not yours. :-) Anyway, I re-created many of the readme changes now...

**Comment by Shinji89** [comment]
ok :)  Anyway i noticed this error in console (on the phone with adb logcat and on the browser with "ionic serve") -> Unrecognized Content-Security-Policy directive '*'. its just a message, the app works great.

**Comment by agamemnus** [comment]
Thanks. The whole whitelist thing missing cdvfile and content is a problem, but needs to be resolved more correctly from within the whitelist plugin itself instead of meta tags. I need to do more research on it, though.

**Comment by falinsin** [comment]
PLease, I need Help.

When In the STEP 4 I use cordova run android --device

But get this:


Error: cmd: Command failed with exit code 1 Error output:
C:\DESARROLLO3\byf\platforms\android\com.flyingsoftgames.xapkreader\beerandfood-library\src\com\google\android\vend
icensing\APKExpansionPolicy.java:20: error: package org.apache.http does not exist
import org.apache.http.NameValuePair;
                      ^
C:\DESARROLLO3\byf\platforms\android\com.flyingsoftgames.xapkreader\beerandfood-library\src\com\google\android\vend
icensing\APKExpansionPolicy.java:21: error: package org.apache.http.client.utils does not exist
import org.apache.http.client.utils.URLEncodedUtils;
                                   ^
C:\DESARROLLO3\byf\platforms\android\com.flyingsoftgames.xapkreader\beerandfood-library\src\com\google\android\vend
icensing\ServerManagedPolicy.java:19: error: package org.apache.http does not exist
import org.apache.http.NameValuePair;
                      ^
C:\DESARROLLO3\byf\platforms\android\com.flyingsoftgames.xapkreader\beerandfood-library\src\com\google\android\vend
icensing\ServerManagedPolicy.java:20: error: package org.apache.http.client.utils does not exist
import org.apache.http.client.utils.URLEncodedUtils;
                                   ^
C:\DESARROLLO3\byf\platforms\android\com.flyingsoftgames.xapkreader\beerandfood-library\src\com\google\android\vend
icensing\APKExpansionPolicy.java:382: error: cannot find symbol
            List<NameValuePair> extraList = URLEncodedUtils.parse(rawExtras, "UTF-8");
                 ^
  symbol:   class NameValuePair
  location: class APKExpansionPolicy
C:\DESARROLLO3\byf\platforms\android\com.flyingsoftgames.xapkreader\beerandfood-library\src\com\google\android\vend
icensing\APKExpansionPolicy.java:382: error: cannot find symbol
            List<NameValuePair> extraList = URLEncodedUtils.parse(rawExtras, "UTF-8");
                                            ^
  symbol:   variable URLEncodedUtils
  location: class APKExpansionPolicy
C:\DESARROLLO3\byf\platforms\android\com.flyingsoftgames.xapkreader\beerandfood-library\src\com\google\android\vend
icensing\APKExpansionPolicy.java:383: error: cannot find symbol
            for (NameValuePair item : extraList) {
                 ^
  symbol:   class NameValuePair
  location: class APKExpansionPolicy
C:\DESARROLLO3\byf\platforms\android\com.flyingsoftgames.xapkreader\beerandfood-library\src\com\google\android\vend
icensing\ServerManagedPolicy.java:266: error: cannot find symbol
            List<NameValuePair> extraList = URLEncodedUtils.parse(rawExtras, "UTF-8");
                 ^
  symbol:   class NameValuePair
  location: class ServerManagedPolicy
C:\DESARROLLO3\byf\platforms\android\com.flyingsoftgames.xapkreader\beerandfood-library\src\com\google\android\vend
icensing\ServerManagedPolicy.java:266: error: cannot find symbol
            List<NameValuePair> extraList = URLEncodedUtils.parse(rawExtras, "UTF-8");
                                            ^
  symbol:   variable URLEncodedUtils
  location: class ServerManagedPolicy
C:\DESARROLLO3\byf\platforms\android\com.flyingsoftgames.xapkreader\beerandfood-library\src\com\google\android\vend
icensing\ServerManagedPolicy.java:267: error: cannot find symbol
            for (NameValuePair item : extraList) {
                 ^
  symbol:   class NameValuePair
  location: class ServerManagedPolicy
Note: C:\DESARROLLO3\byf\platforms\android\com.flyingsoftgames.xapkreader\beerandfood-library\src\com\google\androi
ding\licensing\LicenseChecker.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
10 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':com.flyingsoftgames.xapkreader:library:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by falinsin** [comment]
Is this because my cordova version is 6???

**Comment by agamemnus** [comment]
Yes, needs to be 5.3.1 for the moment.

**Comment by Shashidhar014** [comment]
Can any one tell me how to fix this? 

Below is the system information 

Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v6.2.0
Xcode version: Xcode 7.3.1 Build version 7D1014
