### ISSUE TITLE
Loading assets stuck at 0% / 100% after patch

### ISSUE THREAD

**Issue by unskaa** [agamemnus/cordova-plugin-xapkreader#36]
When I upload a patch the asset loader is unable to load the expansion file. It's just stuck at 0 / 100% and doesn't move.

It doesn't matter if I re-use the same expansion file or upload a new one. Same thing happens.

The app still works, you just gotta hit the back button and relaunch the app after the patch.

Are there any fixes for this?

**Comment by agamemnus** [comment]
Clarification needed: do you have the app in phone memory and expect it to
use the new files, or are you opening a fresh instance and you have to open
and then close it and open it again?

If the former, that is expected behavior. I doubt anyone would complain
that they need to reload the app to use a new version. But, I suppose it is
possible to check one server or another if there was a patch uploaded and
then restart automatically...

If the latter: dang. That is going to be difficult to debug. Wouldn't know
why that is happening. You can disable the downloader (which attempts a
download if there's no expansion file)-for now. Check the megathread first
post to see the code to change...

**Comment by agamemnus** [comment]
Stale. Closing.
